URL: https://github.com/FEDEASLab/fdlb-0004
abstract: Cyclic loading of an inelastic cantilever column using a one component series
  beam model.
archive: fcf
collection-title: Inelastic frames
id: fdlb-0004
medium: CE221
system: CE221
title: Hw12P2A
type: book
