Description of TimeIntegrationConstants
Home > Solution_Library > TimeIntegrationConstants.m
TimeIntegrationConstants
PURPOSE
TIMEINTEGRATIONCONSTANTS constants of time integration strategy
SYNOPSIS
function Int_Constants = TimeIntegrationConstants (TimeStrat,option)
DESCRIPTION
TIMEINTEGRATIONCONSTANTS constants of time integration strategy
  INT_CONSTANTS = TIMEINTEGRATIONCONSTANTS (TIMESTRAT)
  the function determines the constants of the time integration strategy speficied in field
  Type of data structure TIMESTRAT and returns them in vector INT_CONSTRANTS
  the data structure TIMESTRAT contains information about the integration strategy in fiels
      DELTAT = time step (scalar)
      TYPE   = name of integration method (character variable)
      PARAM  = parameters of integration method (vector)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
OneTransientIteration ONETRANSIENTITERATION single equilibrium iteration under transient conditions
TransientIncrement TRANSIENTINCREMENT load incrementation and state advance under transient conditions
Update_TransientState UPDATE_TRANSIENTSTATE final state determination under transient conditions, reset increments and history