URL: https://github.com/FEDEASLab/fdlb-0012
archive: $FEDEASLAB_DEV
archive_location: Gallery/fdlb-0012
author:
- family: Perez
  given: Claudio
id: fdlb-0012
medium: FEDEASLab Dev
programming-language: Matlab
system: FEDEASLab Dev
title: Generalized piecewise limit surface
type: book
