Description of Get_ModelScale
Home > Utilities > Plotting > Get_ModelScale.m
Get_ModelScale
PURPOSE
GET_MODELSCALE determines maximum and minimum element length in Model
SYNOPSIS
function [ModSc,maxL,minL] = Get_ModelScale (Model,Ratio)
DESCRIPTION
GET_MODELSCALE determines maximum and minimum element length in Model
  [MODSC,MAXL,MINL] = GET_MODELSCALE(MODEL,RATIO)
  the function determines a critical scale for the structural model
  in data structure MODEL from the maximum distance MAXL and
  the minimum distance MINL between nodes i and j of line elements;
  the maximum distance MAXL is divided by RATIO (default = 1.5-0.5*MINL/MAXL);
  depending on the value of RATIO the model scale is equal
  to the largest (RATIO<MAXL/MINL) or smallest distance (RATIO>MAXL/MINL)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Label_Model LABEL_MODEL displays element and node numbers and global axes in the current window
Plot_2dCurvDistr PLOT_2dCURVDISTR plot curvature distribution of 2d linear elastic frame elements
Plot_2dMomntDistr PLOT_2dMOMNTDISTR plots moment distribution for 2d frame elements in current window
Plot_AxialForces PLOT_AXIALFORCES plot axial forces in current window
Plot_DeformedStructure PLOT_DEFORMEDSTRUCTURE plot deformed shape of the structure
Plot_ElemLoading PLOT_ELEMLOADING display element loading in current window
Plot_IPVarDistr PLOT_IPVARDISTR plots distribution of integration point variables of elements with sections
Plot_Model PLOT_MODEL plots the original or deformed geometry of the structural model
Plot_NodalForces PLOT_NODALFORCES display nodal forces in current window
Plot_OpenPlasticHinges PLOT_OPENPLASTICHINGES display plastic hinge locations in original or deformed configuration
Plot_PlasticHinges PLOT_PLASTICHINGES display plastic hinge locations in current window
Plot_Releases PLOT_RELEASES display element releases in current window