Description of GeomTran_2dFrm
Home > Element_Library > GeomTran_2dFrm.m
GeomTran_2dFrm
PURPOSE
GEOMTRAN_2dFRM kinematic matrices and deformations for a 2-node 2d frame element
SYNOPSIS
function [ag,bg,ab,v,Dv,DDv] = GeomTran_2dFrm (option,xyz,GeomData,u,Du,DDu)
DESCRIPTION
GEOMTRAN_2dFRM kinematic matrices and deformations for a 2-node 2d frame element
  [AG,BG,AB,V,DV,DDV] = GEOMTRAN_2dFRM (OPTION,XYZ,GEOMDATA,U,DU,DDU)
  the function determines the kinematic matrix AG from the global to the basic reference system,
  the static matrix BG from the basic to the global reference system,
  and the kinematic matrix AB from the global to the local reference system
  as well as the element deformation vector V and its increments DV and DDV
  from the node displacement array U and its increments DU and DDU
  for a 2-node 2d frame element with end node coordinates XYZ;
  OPTION is a character variable with one of three values:
  'linear','PDelta' and 'corotational' for linear, P-Delta and corotational geometry, resp.
  GEOMDATA is a data structure with information about rigid joint offsets in field JNTOFF,
  (first column for node i, second column for node j)
CROSS-REFERENCE INFORMATION
This function calls:
Large2du2v_Frm LARGE2DU2V_FRM determine 2d frame element deformations from end displacements
TranJnt TRANJNT sets up transformation matrix for finite size joints
This function is called by:
Dinel2dFrm_EBwDF DINEL2dFRM_EBwDF 2d-frame element with distributed inelasticity (displacement formulation)
Dinel2dFrm_EBwFF DINEL2dFRM_EBwFF 2d-frame element with distributed inelasticity (force formulation)
Inel2dFrm_wLHNMYS INEL2dFRM_wLHNMYS 2d linear elastic frame element with linear plastic hardening axial-flexure hinges
Inel2dFrm_wLPPM INEL2dFRM_wLPPM 2d frame linear elastic element perfectly plastic flexural response
Inel2dFrm_wOneComp INEL2dFRM_wONECOMP one component 2d frame element with rigid-linear hardening end hinges
Inel2dFrm_wTwoComp INEL2dFRM_wTWOCOMP two component 2d frame element (linear + linear-perfectly plastic)
LE2dFrm LE2dFRM 2d LE frame element under linear or nonlinear geometry
LE2dFrm_wPdelta LE2dFRM 2d linear elastic frame element with P-delta effect under linear or nonlinear geometry