id: fdlb-0012
title: Generalized piecewise limit surface
abstract: Development of a function that sets up the block diagonal matrix of element
  limit-surface equations for plastic analysis of a structural model using
  FEDEASLab.
author:
- family: Perez
  given: Claudio
collection-title: Plastic analysis
programming-language: Matlab
distribution: FEDEASLab Dev
