Description of Rectangle2Fiber
Home > Utilities > PreProcessing > Rectangle2Fiber.m
Rectangle2Fiber
PURPOSE
RECTANGLE2FIBER integration points and weights for 2d-integration of a rectangle
SYNOPSIS
function [yfib,zfib,wfib] = Rectangle2Fiber (patcoor,IntTyp,nyfib,nzfib)
DESCRIPTION
RECTANGLE2FIBER integration points and weights for 2d-integration of a rectangle
  [YFIB,ZFIB,WFIB] = RECTANGLE2FIBER (PATCOOR,INTTYP,NYFIB,NZFIB)
  the function determines the locations in vectors YFIB and ZFIB and the integration weights
  in vector WFIB for the 2d integration of a rectangle with the integration scheme
  in character array INTTYP and the number of integration points in the y-direction in NYFIB
  and in the z-direction in NZFIB, respectively;
  the geometry of the rectangle is supplied by specifying the
  coordinates of opposite corners in array PATCOOR [ y1 z1 (top left); y2 z2 (bottom right)]
  (NOTE: right handed local coordinate system x-y-z!)
  INTTYP can be either 'Midpoint', 'Gauss', Lobatto' or 'Trap'
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Create_IPMesh4MultRectShape CREATE_IPMESH4MULTRECTSHAPE fiber discretization for section of several rectangular patches
Create_IPMesh4Rect CREATE_IPMESH4RECT coordinates, weights and material IDs for rectangular section with cover
Create_IPMesh4WFShape CREATE_IPMESH4WFSHAPE coordinates, weights and material IDs for wide flange section