URL: https://github.com/FEDEASLab/fdlb-0011
archive: $FEDEASLAB_DEV
archive_location: Gallery/fdlb-0011
collection-title: Section analysis
id: fdlb-0011
medium: FEDEASLab Dev
programming-language: Matlab
system: FEDEASLab Dev
title: Yield surface evolution
type: book
