Description of Create_RectPatch
Home > Utilities > PreProcessing > Create_RectPatch.m
Create_RectPatch
PURPOSE
CREATE_RECTPATCH generate corner coordinates of rectangular patch for given reference point
SYNOPSIS
function yz = Create_RectPatch (ty,tz,sy,sz)
DESCRIPTION
CREATE_RECTPATCH generate corner coordinates of rectangular patch for given reference point
  YZ = CREATE_RECTPATCH (TY,TZ,SY,SZ)
  the function generates the corner coordinates of a rectangular patch TY x TZ, where TY is
  the dimension in Y and TZ is the dimension in Z, with respect to a reference point at a
  distance SY in Y and SZ in Z from the centroid of the patch;
  the function returns the corner coordinates in the 1x4 array YZ = [Y1 Z1 Y2 Z2] where
  1 refers to the upper left corner and 2 to the lower right corner of the rectangular patch
  Section coordinate system:
                                   ^ y
                                   |
                               ----+----
                               |   |   |
                               |   |   |
                         z <---+---+   |
                               |       |
                               |       |
                               ---------
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Create_BoxOutline CREATE_BOXOUTLINE generate geometry outline for box section
Create_BoxwOvhOutline CREATE_BOXwOVHOUTLINE generate geometry outline for box section
Create_CSecOutline CREATE_CSECOUTLINE generate geometry outline for C-section
Create_IPMesh4WFShape CREATE_IPMESH4WFSHAPE coordinates, weights and material IDs for wide flange section
Create_ISecOutline CREATE_ISECOUTLINE generate geometry outline for I-section
Create_LSecOutline CREATE_LSECOUTLINE generate geometry outline for L-section
Create_RectShape CREATE_RECTSHAPE generate geometry outline and assign material properties for rectangle
Create_RectwCovOutline CREATE_RECTwCOVOUTLINE generate geometry outline for rectangular section with cover
Create_SSecOutline CREATE_SSECOUTLINE generate geometry outline for C-section
Create_TSecOutline CREATE_TSECOUTLINE generate geometry outline for T-section