archive: $FEDEASLAB_DEV
archive_location: Gallery/fdlb-0001
collection-title: Section analysis
id: fdlb-0001
medium: CE221
note: 'doc_manifest: ["file1.ext", "file2.ext", ''img/'']'
programming-language: Matlab
system: CE221
title: Hw12P1A
type: book
