Description of ElementLoading
Home > Element_Library > ElementLoading.m
ElementLoading
PURPOSE
ELEMENTLOADING determines current distributed element load value
SYNOPSIS
function wC = ElementLoading (w0,lamda,LdId)
DESCRIPTION
ELEMENTLOADING determines current distributed element load value
  WC = ELEMENTLOADING (w0,LAMDA,LDID);
  function determines the current distributed element load values as the product of the
  user specified reference values in vector W0 and the current load factor(s) in row vector
  LAMDA; the load history ID for distributed element loads is specified in row vector LDID
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Dinel2dFrm_EBwDF DINEL2dFRM_EBwDF 2d-frame element with distributed inelasticity (displacement formulation)
Dinel2dFrm_EBwFF DINEL2dFRM_EBwFF 2d-frame element with distributed inelasticity (force formulation)
Inel2dFrm_wLHNMYS INEL2dFRM_wLHNMYS 2d linear elastic frame element with linear plastic hardening axial-flexure hinges
Inel2dFrm_wOneComp INEL2dFRM_wONECOMP one component 2d frame element with rigid-linear hardening end hinges