Description of kg_2dFrm
Home > Element_Library > kg_2dFrm.m
kg_2dFrm
PURPOSE
KG_2dFRM geometric stiffness matrix for 2-node 2d frame element for different options
SYNOPSIS
function kg = kg_2dFrm (option,xyz,u,q)
DESCRIPTION
KG_2dFRM geometric stiffness matrix for 2-node 2d frame element for different options
  KG = KG_2dFRM (OPTION,XYZ,U,Q)
  the function determines the geometric stiffness matrix KG of a 2-node 2d frame element
  with end coordinates in array XYZ (node i corresponds to first column and node j to second);
  the geometric stiffness matrix depends on the node displacement values in array U (ndfx2)
  in the global reference system and on the basic force vector Q;
  OPTION is a character variable with one of three values:
  'linear','PDelta' and 'corotational' for linear, P-Delta and corotational geometry, resp.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Dinel2dFrm_EBwDF DINEL2dFRM_EBwDF 2d-frame element with distributed inelasticity (displacement formulation)
Dinel2dFrm_EBwFF DINEL2dFRM_EBwFF 2d-frame element with distributed inelasticity (force formulation)
Inel2dFrm_wLHNMYS INEL2dFRM_wLHNMYS 2d linear elastic frame element with linear plastic hardening axial-flexure hinges
Inel2dFrm_wLPPM INEL2dFRM_wLPPM 2d frame linear elastic element perfectly plastic flexural response
Inel2dFrm_wOneComp INEL2dFRM_wONECOMP one component 2d frame element with rigid-linear hardening end hinges
Inel2dFrm_wTwoComp INEL2dFRM_wTWOCOMP two component 2d frame element (linear + linear-perfectly plastic)
LE2dFrm LE2dFRM 2d LE frame element under linear or nonlinear geometry
LE2dFrm_wPdelta LE2dFRM 2d linear elastic frame element with P-delta effect under linear or nonlinear geometry