Description of Extract_Sec2MatState
Home > Section_Library > Extract_Sec2MatState.m
Extract_Sec2MatState
PURPOSE
EXTRACT_SEC2MATSTATE extract material state from section state
SYNOPSIS
function MatState = Extract_Sec2MatState (m,as,SecState)
DESCRIPTION
EXTRACT_SEC2MATSTATE extract material state from section state
  MATSTATE = EXTRACT_SEC2MATSTATE (M,AS,SECSTATE)
  function extracts from data structure SECSTATE the necessary information
  for material point M, and returns it in data structure MATSTATE;
  it needs compatibility array AS to determine material strains from section deformations
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
HomoCircSecw1dMat HOMOCIRCSECw1dMAT response of homogeneous circular section with uniaxial material
HomoRectSecw1dMat HOMORECTSECw1dMAT response of homogeneous rectangular section with uniaxial material
HomoWFSecw1dMat HOMOWFSECw1dMAT response of homogeneous wide flange (WF) section with uniaxial material
MultRectSecw1dMat MULTRECTSECw1dMAT response for section of rectangular patches and bars with uniaxial material
ReCircSecw1dMat RECIRCSECw1dMAT response of reinforced circular section with uniaxial materials
ReRectSecw1dMat RERECTSECw1dMAT response of reinforced rectangular section with uniaxial materials