URL: https://github.com/FEDEASLab/fdlb-0008
archive: $FEDEASLAB_DEV
archive_location: Gallery/fdlb-0008
collection-title: Reliability Analysis
id: fdlb-0008
medium: FEDEASLab Dev
programming-language: Matlab
system: FEDEASLab Dev
title: Built-up column
type: book
