Description of LoadFactorControl
Home > Solution_Library > LoadFactorControl.m
LoadFactorControl
PURPOSE
LOADFACTORCONTROL determine load factor increment under load control strategy
SYNOPSIS
function SolStrat = LoadFactorControl (action,SolStrat,detKf,Pref,Ut,DUr)
DESCRIPTION
 LOADFACTORCONTROL determine load factor increment under load control strategy
  SOLSTRAT = LOADFACTORCONTROL(ACTION,SOLSTRAT,KL,KU,PREF,UT,DUR)
  the function determines the load factor increment in field DLAM of data structure SOLSTRAT
  under the specified load control strategy in field LCTYPE of SOLSTRAT;
  ACTION is a character variable that distinguishes various load control stages, i.e.
  initialization, incrementation and iteration; accordingly, the choices are
  ACTION = 'init': initialization of load control parameters in field HIST of SOLSTRAT
  ACTION = 'incr': determination of DLAM during load incrementation; parameter update in HIST
  ACTION = 'iter': determination of DLAM during equilibrium iteration (the following load
                   control methods are currently supported: 'MinDispNorm' and 'KeyDOF'
  KL and KU are the lower and upper diagonal LU components of the tangent stiffness matrix,
  PREF is the reference force vector and UT the corresponding displacement vector under PREF,
  DUR is the vector of displacement increments under the current unbalance force vector
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Increment INCREMENT load incrementation and state advance under static conditions
Initialize INITIALIZE initialize analysis variables in STATE and load control parameters in SOLSTRAT
OneIteration ONEITERATION single equilibrium iteration under static conditions