Description of OneIteration
Home > Solution_Library > OneIteration.m
OneIteration
PURPOSE
ONEITERATION single equilibrium iteration under static conditions
SYNOPSIS
function [State,SolStrat] = OneIteration (Model,ElemData,Loading,State,SolStrat)
DESCRIPTION
 ONEITERATION single equilibrium iteration under static conditions
  [STATE,SOLSTRAT] = ONEITERATION (MODEL,ELEMDATA,LOADING,STATE,SOLSTRAT)
  the function performs a single equilibrium iteration under the applied loading
  and determines the corresponding displacement increments under static conditions;
  information about the state of the structure is updated in STATE and
  information about the parameters of the solution strategy is updated in SOLSTRAT;
  MODEL is a data structure with information about the structural model, ELEMDATA is
  a cell array with element properties, and LOADING is a data structure with information
  about applied force and imposed displacement patterns with corresponding load histories
CROSS-REFERENCE INFORMATION
This function calls:
LoadFactorControl LOADFACTORCONTROL determine load factor increment under load control strategy
StateDetermination STATEDETERMINATION structure state determination under static conditions
This function is called by:
Iterate ITERATE equilibrium iterations until convergence under static conditions