Description of DefGeom_2dFrm
Home > Element_Library > DefGeom_2dFrm.m
DefGeom_2dFrm
PURPOSE
DEFGEOM_2dFRM determines current length and corotational diad of 2-node, 2d frame element
SYNOPSIS
function [L,T] = DefGeom_2dFrm (xyz)
DESCRIPTION
DEFGEOM_2dFRM determines current length and corotational diad of 2-node, 2d frame element
  [L,T] = DEFGEOM_2dFRM (XYZ);
  the function determines the length L and the corotational diad T
  of a 2d frame element in the current configuration
  from the end node coordinates XYZ (column 1 for node i, column 2 for node j);
  the corotational diad is given in matrix T whose columns correspond to axes x and y, resp.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
DeformShape2dFrm DEFORMSHAPE2dFRM deformed shape of linear elastic, uniform, prismatic 2d frame element
DeformShape2dFrm_wCurvIntp DEFORMSHAPE2dFRM_wCURVINTP deformed shape of 2d frame element from curvatures
DeformShape2dFrm_wDispIntp DEFORMSHAPE2dFRM_wDISPINTP deformed shape of 2d frame element with cubic polynomials