Description of DeformShape2dFrm_wDispIntp
Home > Element_Library > DeformShape2dFrm_wDispIntp.m
DeformShape2dFrm_wDispIntp
PURPOSE
DEFORMSHAPE2dFRM_wDISPINTP deformed shape of 2d frame element with cubic polynomials
SYNOPSIS
function [XYd,xyd] = DeformShape2dFrm_wDispIntp (xyz,ElemData,u,v,MAGF,nsub)
DESCRIPTION
DEFORMSHAPE2dFRM_wDISPINTP deformed shape of 2d frame element with cubic polynomials
  [XYd,xyd] = DEFORMSHAPE2dFRM_wDISPINTP (XYZ,ELEMDATA,U,V,MAGF,NSUB)
  The function returns the global coordinates of the magnified deformed shape
  of a 2d frame element under large end displacements in array XYd,
  and the local coordinates of the magnified deformed shape in array xyd.
  Input arguments are the end node coordinates in array XYZ, the element
  properties in cell array ELEMDATA, and the end node displacements in vector U.
  Optional arguments are the end deformations V for elements with releases
  or plastic hinges (these can be supplied in a data structure with fields VE or V),
  the magnification factor MAGF (default=10), and the number
  of intermediate points NSUB (default=100) for the deformed shape.
  and NSUB for the number of intermediate points for the deformed shape;
  The function uses Hermite cubic interpolation polynomials for the
  transverse displacements.
CROSS-REFERENCE INFORMATION
This function calls:
DefGeom_2dFrm DEFGEOM_2dFRM determines current length and corotational diad of 2-node, 2d frame element
Large2du2v_Frm LARGE2DU2V_FRM determine 2d frame element deformations from end displacements
TranJnt TRANJNT sets up transformation matrix for finite size joints
This function is called by: