Description of GeomTran_3dFrm
Home > Element_Library > GeomTran_3dFrm.m
GeomTran_3dFrm
PURPOSE
GEOMTRAN_3dFRM kinematic matrices and deformations for a 2-node 3d frame element
SYNOPSIS
function [ag,bg,ab,v,Dv,DDv] = GeomTran_3dFrm (option,xyz,GeomData,u,Du,DDu)
DESCRIPTION
GEOMTRAN_3dFRM kinematic matrices and deformations for a 2-node 3d frame element
  [AG,BG,AB,V,DV,DDV] = GEOMTRAN_3dFRM (OPTION,XYZ,GEOMDATA,U,DU,DDU)
  the function determines the kinematic matrix AG from the global to the basic reference system,
  the static matrix BG from the basic to the global reference system,
  and the kinematic matrix AB from the global to the local reference system
  as well as the element deformation vector V and its increments DV and DDV
  from the node displacement array U and its increments DU and DDU
  for a 2-node 3d frame element with end node coordinates XYZ;
  OPTION is a character variable with one of three values:
  'linear','PDelta' and 'corotational' for linear, P-Delta and corotational geometry, resp.
  GEOMDATA is a data structure with information about rigid joint offsets in field JNTOFF
  (first column for node i, second column for node j),
  and orientation (direction cosines) of the local y-axis in vector YORNT
CROSS-REFERENCE INFORMATION
This function calls:
DefGeom_3dFrm DEFGEOM_3dFRM determines current length and corotational triad of 2-node, 3d frame element
Large3du2v_Frm LARGE3DU2V_FRM determine 3d frame element deformations from end displacements
TranJnt TRANJNT sets up transformation matrix for finite size joints
This function is called by:
LE3dFrm LE3dFRM 3d linear frame element under linear or nonlinear geometry