Description of TranJnt
Home > Element_Library > TranJnt.m
TranJnt
PURPOSE
TRANJNT sets up transformation matrix for finite size joints
SYNOPSIS
function aj = TranJnt (jntoff)
DESCRIPTION
TRANJNT sets up transformation matrix for finite size joints
  AJ = TRANJNT (JNTOFF)
  the function sets up the transformation matrix AJ for finite size joints of 2d and 3d frame elements;
  the rigid joint offsets at the element ends are specified in array JNTOFF
  with the first column corresponding to node i and the second column to node j
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
DeformShape2dFrm DEFORMSHAPE2dFRM deformed shape of linear elastic, uniform, prismatic 2d frame element
DeformShape2dFrm_wCurvIntp DEFORMSHAPE2dFRM_wCURVINTP deformed shape of 2d frame element from curvatures
DeformShape2dFrm_wDispIntp DEFORMSHAPE2dFRM_wDISPINTP deformed shape of 2d frame element with cubic polynomials
GeomTran_2dFrm GEOMTRAN_2dFRM kinematic matrices and deformations for a 2-node 2d frame element
GeomTran_3dFrm GEOMTRAN_3dFRM kinematic matrices and deformations for a 2-node 3d frame element