Description of Localize
Home > Basic > Localize.m
Localize
PURPOSE
LOCALIZE returns the node coordinates and id array of element
SYNOPSIS
function [xyz,id] = Localize (Model,el)
DESCRIPTION
LOCALIZE returns the node coordinates and id array of element
  [XYZ,ID] = LOCALIZE (MODEL,EL)
  the function returns the node coordinates XYZ and the id array ID
  of the element with number EL for the structural model specified in data structure MODEL
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
A_matrix A_MATRIX kinematic matrix of structural model with 2d/3d truss and 2d frame elements
B_matrix B_MATRIX static matrix of structural model with 2d/3d truss and 2d frame elements
Fs_matrix FS_MATRIX block diagonal matrix of element flexibity matrices for structural model
Ks_matrix KS_MATRIX block diagonal matrix of basic element stiffness matrices for structural model
Q0_vector Q0_VECTOR initial (fixed-end) force vector for structural model
V0_vector V0_VECTOR initial element deformation vector for the structural model