ElmLenOr - FEDEASLab
Home > src > Basic > ElmLenOr.m
ElmLenOr
Purpose
ELMLENOR element length and x-axis orientation (direction cosines)
Synopsis
function [L,dcx] = ElmLenOr (xyz) ## Description
ELMLENOR element length and x-axis orientation (direction cosines)
  [L,DCX] = ELMLENOR (XYZ);
  the function determines the length L and x-axis orientation of an element
  with end node coordinates XYZ (column 1 for node i, column 2 for node j);
  the direction cosines for the element x-axis are reported in vector DCX
Cross-Reference Information
This function calls:
This function is called by:
Check3dFrmAxes CHECK3dFRMAXES check that y-axis is not co-linear with element chord
Inel2dFrm INEL2dFRM inelastic 2d frame element with different basic element types
InelTruss INELTRUSS 2d/3d inelastic truss element under linear or nonlinear geometry
DeformShape2dFrm DEFORMSHAPE2dFRM deformed shape of linear elastic, uniform, prismatic 2d frame element
DeformShape2dFrm_wDispIntp DEFORMSHAPE2dFRM_wDISPINTP deformed shape of 2d frame element with cubic polynomials
DeformShape3dFrm DEFORMSHAPE3dFRM deformed shape of linear elastic, uniform, prismatic 3d frame element
DeformShape3dFrm_wDispIntp DEFORMSHAPE3dFRM_wDISPINTP deformed shape of 3d frame element with cubic polynomials
DeformShape2dFrm_wCurvIntp DEFORMSHAPE2dFRM_wCURVINTP deformed shape of 2d frame element from curvatures
DeformShape3dFrm_wCurvIntp DEFORMSHAPE3dFRM_wCURVINTP deformed shape of 3d frame element from curvatures
Dinel2dFrm_EBwDF DINEL2dFRM_EBwDF 2d-frame element with distributed inelasticity (displacement formulation)
Dinel3dFrm_EBwDF DINEL3DFRM_EBwDF Euler-Bernoulli 3d-frame element with distributed inelasticity (displacement formulation)
Mass4Taper2dFrm_wDF MASS4TAPER2dFRM_wDF consistent mass matrix for tapered 2d frame element with displ interpolation
LE2dFrm LE2dFRM 2d LE frame element under linear or nonlinear geometry
LE2dFrm_wPdelta LE2dFRM 2d linear elastic frame element with P-delta effect under linear or nonlinear geometry
LE2dFrm_wVarIDF LE2dFRM_wVARIDF 2d LE frame element with variable cross section under linear or NL geometry
LE2dFrm_wVarIFF LE2dFRM_wVARIFF 2d LE frame element with variable cross section under linear or NL geometry
LE3dFrm LE3dFRM 3d linear frame element under linear or nonlinear geometry
LETruss LETRUSS 2d/3d linear truss element under linear or nonlinear geometry
Mass4Prism2dFrm MASS4PRISM2dFRM consistent mass matrix for prismatic 2d frame element
A_matrix A_MATRIX kinematic matrix of structural model with 2d/3d truss and 2d frame elements
Aj_matrix AJ_MATRIX kinematic matrix of structural model with 2d/3d truss and 2d frame elements
B_matrix B_MATRIX equilibrium matrix of structural model with 2d/3d truss and 2d frame elements
Fs_matrix FS_MATRIX block diagonal matrix of element flexibity matrices for structural model
Kf_matrix KF_MATRIX stiffness matrix at free dofs of structural model
Ks_matrix KS_MATRIX block diagonal matrix of basic element stiffness matrices for structural model
Q0_vector Q0_VECTOR initial (fixed-end) force vector for structural model
V0_vector V0_VECTOR initial element deformation vector for the structural model
DefGeom_2dFrm DEFGEOM_2dFRM determines current length and corotational diad of 2-node, 2d frame element
DefGeom_3dFrm DEFGEOM_3dFRM determines current length and corotational triad of 2-node, 3d frame element
GeomTran_2dFrm GEOMTRAN_2dFRM kinematic matrices and deformations for a 2-node 2d frame element
GeomTran_Truss GEOMTRAN_TRUSS kinematic matrices and deformations for a 2-node truss element
Large2du2v_Frm LARGE2DU2V_FRM determine 2d frame element deformations from end displacements
kg_2dFrm KG_2dFRM geometric stiffness matrix for 2-node 2d frame element for different options
kg_Truss KG_TRUSS geometric stiffness matrix for 2d/3d 2-node truss element for different options
Draw_Arrow DRAW_ARROW draws 2d or 3d arrow
Get_IPVarDistr PLOT_IPVARDISTR plots distribution of integration point variables of elements with sections
Label_2dMoments LABEL_2dMOMENTS label end moment values for 2d frame elements in current window
Label_AxialForces LABEL_AXIALFORCES label axial force values in current window
Plot_2dCurvDistr PLOT_2dCURVDISTR plot curvature distribution of 2d linear elastic frame elements
Plot_2dMomntDistr PLOT_2dMOMNTDISTR plots moment distribution for 2d frame elements in current window
Plot_AxialForces PLOT_AXIALFORCES plot axial forces in current window
Plot_ForcDistr PLOT_FORCDISTR plots internal force distribution for truss and frame elements in ElemList
Plot_IPVarDistr PLOT_IPVARDISTR plots distribution of integration point variables of elements with sections
Get_HngPos4DefoElem GET_HNGPOS4DEFOELEM determine axial and flexural hinge position for deformed element
Get_ModelScale GET_MODELSCALE determines maximum and minimum element length in Model
Label_Model LABEL_MODEL displays element and node numbers and global axes in the current window
Plot_ElemLoading PLOT_ELEMLOADING display element loading in current window
Plot_OpenPlasticHinges PLOT_OPENPLASTICHINGES display plastic hinge locations in original or deformed configuration
Plot_PlasticHinges PLOT_PLASTICHINGES display plastic hinge locations in current window
Plot_Releases PLOT_RELEASES display element releases in current window
Add_OpenPHIndx2Post ADD_OPENPHINDX2POST add index to POST for open plastic hinges in elements
Add_Brace2Frame ADD_BRACE2FRAME adds brace elements to a bay of a frame
A_matrix A_MATRIX kinematic matrix of structural model with 2d/3d truss and 2d frame elements
B_matrix B_MATRIX equilibrium matrix of structural model with 2d/3d truss and 2d frame elements
Fs_matrix FS_MATRIX block diagonal matrix of element flexibity matrices for structural model
Ks_matrix KS_MATRIX block diagonal matrix of basic element stiffness matrices for structural model
Q0_vector Q0_VECTOR initial (fixed-end) force vector for structural model
V0_vector V0_VECTOR initial element deformation vector for the structural model
Dinel2dFrm_EBwDF DINEL2dFRM_EBwDF 2d-frame element with distributed inelasticity (displacement formulation)
Inel2dFrm INEL2dFRM inelastic 2d frame element with different basic element types
InelTruss INELTRUSS 2d/3d inelastic truss element under linear or nonlinear geometry
LE2dFrm LE2dFRM 2d LE frame element under linear or nonlinear geometry
Draw_Arrow DRAW_ARROW draws 2d or 3d arrow
Label_2dMoments LABEL_2dMOMENTS label end moment values for 2d frame elements in current window
Label_AxialForces LABEL_AXIALFORCES label axial force values in current window
Label_Model LABEL_MODEL displays element and node numbers and global axes in the current window
Plot_2dCurvDistr PLOT_2dCURVDISTR plot curvature distribution of 2d linear elastic frame elements
Plot_2dMomntDistr PLOT_2dMOMNTDISTR plots moment distribution for 2d frame elements in current window
Plot_AxialForces PLOT_AXIALFORCES plot axial forces in current window
Plot_DeformedStructure PLOT_DEFORMEDSTRUCTURE plot deformed shape of the structure
Plot_ElemLoading PLOT_ELEMLOADING display element loading in current window
Plot_PlasticHinges PLOT_PLASTICHINGES display plastic hinge locations in current window
Plot_Releases PLOT_RELEASES display element releases in current window
A_matrix A_MATRIX kinematic matrix of structural model with 2d/3d truss and 2d frame elements
B_matrix B_MATRIX equilibrium matrix of structural model with 2d/3d truss and 2d frame elements
Fs_matrix FS_MATRIX block diagonal matrix of element flexibity matrices for structural model
Ks_matrix KS_MATRIX block diagonal matrix of basic element stiffness matrices for structural model
Q0_vector Q0_VECTOR initial (fixed-end) force vector for structural model
V0_vector V0_VECTOR initial element deformation vector for the structural model
InelTruss INELTRUSS 2d/3d inelastic truss element under linear or nonlinear geometry
LE2dFrm LE2dFRM 2d LE frame element under linear or nonlinear geometry
Draw_Arrow DRAW_ARROW draws 2d or 3d arrow