Home > Basic > A_matrix.m
A_matrix
PURPOSE
A_MATRIX kinematic matrix of structural model with 2d/3d truss and 2d frame elements
SYNOPSIS
function A = A_matrix (Model)
DESCRIPTION
A_MATRIX kinematic matrix of structural model with 2d/3d truss and 2d frame elements
  A = A_MATRIX (MODEL)
  the function forms the kinematic matrix A for all degrees of freedom and
  all element deformations of the structural model specified in data structure MODEL;
  the function is currently limited to 2d/3d truss and 2d frame elements
CROSS-REFERENCE INFORMATION
This function calls:
ElmLenOr ELMLENOR element length and x-axis orientation (direction cosines)
Localize LOCALIZE returns the node coordinates and id array of element
This function is called by:
PlasticAnalysis_wUBT PLASTICANALYSIS_wUBT collapse load factor and deformation increments by upper bound theorem of plastic analysis
S_DisplMethod % script for displacement method of structural analysis