Description of B_matrix
Home > Basic > B_matrix.m
B_matrix
PURPOSE
B_MATRIX static matrix of structural model with 2d/3d truss and 2d frame elements
SYNOPSIS
function B = B_matrix (Model)
DESCRIPTION
B_MATRIX static matrix of structural model with 2d/3d truss and 2d frame elements
  B = B_MATRIX (MODEL)
  the function forms the static matrix B for all degrees of freedom and
  all basic forces of the structural model specified in data structure MODEL;
  the function is currently limited to 2d/3d truss and 2d frame elements
CROSS-REFERENCE INFORMATION
This function calls:
ElmLenOr ELMLENOR element length and x-axis orientation (direction cosines)
Localize LOCALIZE returns the node coordinates and id array of element
This function is called by:
PlasticAnalysis_wLBT PLASTICANALYSIS_wLBT collapse load factor and basic element forces by lower bound theorem of plastic analysis
S_ForceMethod % script for force method of structural analysis