Description of Q0_vector
Home > Basic > Q0_vector.m
Q0_vector
PURPOSE
Q0_VECTOR initial (fixed-end) force vector for structural model
SYNOPSIS
function Q0 = Q0_vector (Model,ElemData)
DESCRIPTION
Q0_VECTOR initial (fixed-end) force vector for structural model
  Q0 = Q0_VECTOR (MODEL,ELEMDATA)
  the function sets up the initial (fixed-end) force vector Q0 for the structural model
  specified in data structure MODEL with element property information in cell array ELEMDATA
CROSS-REFERENCE INFORMATION
This function calls:
ElmLenOr ELMLENOR element length and x-axis orientation (direction cosines)
Localize LOCALIZE returns the node coordinates and id array of element
This function is called by:
S_DisplMethod % script for displacement method of structural analysis