Description of Animate_ResponsewHngHist
Home > Utilities > Plotting > Animate_ResponsewHngHist.m
Animate_ResponsewHngHist
PURPOSE
ANIMATE_RESPONSEwHNGHIST interactive or recorded response and plastic hinge history
SYNOPSIS
function Animate_ResponsewHngHist (Model,ElemData,Post,PlotOpt)
DESCRIPTION
ANIMATE_RESPONSEwHNGHIST interactive or recorded response and plastic hinge history
  ANIMATE_RESPONSEwHNGHIST (MODEL,ELEMDATA,POST,PLOTOPT)
  the function generates the response and plastic hinge history of the model
  either interactively or in a recorded video file;
  the data structure MODEL contains information about the structural model, and
  element property information is provided in cell array ELEMDATA;
  the data structure POST contains the structure response history
  PLOTOPT is a data structure for controlling the response and plastic
  hinge display with the following fields:
    MAGF:  magnification factor for deformed shape (default=10)
    NodSF: scale factor for size of node symbol (default=1)
    HngSF: scale factor for size of plastic hinge symbol (default=1)
    HOfSF: factor for offset of plastic hinge symbol from element end (default=1)
    Inter: switch for interactive animation (yes) or video generation (no=default)
    MovieFN:   video file name (default=Movie)
    PauseDur:  pause duration for screen animation in sec (default=0)
    FrameRate: frames per second for video recording (default=30)
    LnClr: line color for deformed shape (default='r' for red)
    PlJnt: switch for plotting joint offsets (default='yes')
    Nskip: number   of response states to skip (default=1, i.e. no skipping)
    Nstrt: first response state to plot (default=2, i.e. first after zero state)
    Npend: last  response state to plot (default=end of Post)
    ShowT: switch for showing time step number on screen (default=no)
    PlCrd: display element chords with deformed shape (default='no')
CROSS-REFERENCE INFORMATION
This function calls:
Plot_DeformedStructure PLOT_DEFORMEDSTRUCTURE plot deformed shape of the structure
Plot_Model PLOT_MODEL plots the original or deformed geometry of the structural model
Plot_OpenPlasticHinges PLOT_OPENPLASTICHINGES display plastic hinge locations in original or deformed configuration
Plot_PlasticHinges PLOT_PLASTICHINGES display plastic hinge locations in current window
This function is called by: