Description of Animate_EventSequence
Home > Utilities > Plotting > Animate_EventSequence.m
Animate_EventSequence
PURPOSE
ANIMATE_EVENTSEQUENCE generate plot sequence with location of plastic hinges for each event
SYNOPSIS
function Animate_EventSequence (Model,ElemData,Ufh,Qh,PlotOpt)
DESCRIPTION
ANIMATE_EVENTSEQUENCE generate plot sequence with location of plastic hinges for each event
  ANIMATE_EVENTSEQUENCE (MODEL,ELEMDATA,UFH,QH,PLOTOPT)
  the function generates a plot sequence of the deformed structural model with the plastic hinge
  locations at each event, thus animating the plastic hinge formation sequence;
  the free global dof displacement history is provided in array UFH, with one column for each event,
  and the corresponding basic force history in array QH, with one column for each event;
  the data structure MODEL contains information about the structural model, while
  ELEMDATA contains element property information; there are two options for supplying
  the plastic capacities of the structural elements in ELEMDATA:
  (a) as fields Np for axial and Mp for flexural of the cell array ELEMDATA
  (a) as a column vector
  PLOTOPT is a data structure for controlling the plastic hinge display
  with the following fields:
    HngSF: scale factor for size of plastic hinge symbol (default = 1)
    HOfSF: factor for offset of the plastic hinge symbol from element end (default = 1)
    LnClr: line color for deformed shape (default='r' for red)
    CdClr: line color for element chord (default='k' for black)
    PlJnt: switch for plotting joint offsets (default='yes')
    PlCrd: display element chords with deformed shape (default='no')
    NodSF: factor for relative size of node symbol (default=1)
    tol:   relative tolerance for plastic capacity check;
           absolute tolerance for plastic rotation check
    Inter: switch for interactive animation (yes, default) or video generation (no)
  MovieFN: video file name (default=Movie)
  PauseDur: pause duration for screen animation in sec (default=0)
  FrameRate: frames per second for video recording (default=30)
  Nsub :  number of interpolated intermediate plots between events for movie
CROSS-REFERENCE INFORMATION
This function calls:
Plot_DeformedStructure PLOT_DEFORMEDSTRUCTURE plot deformed shape of the structure
Plot_Model PLOT_MODEL plots the original or deformed geometry of the structural model
Plot_PlasticHinges PLOT_PLASTICHINGES display plastic hinge locations in current window
This function is called by: