Description of Draw_Arrow
Home > Utilities > Plotting > Draw_Arrow.m
Draw_Arrow
PURPOSE
DRAW_ARROW draws 2d or 3d arrow
SYNOPSIS
function varargout = Draw_Arrow (Astr,Aend,Aln,PlotOpt)
DESCRIPTION
DRAW_ARROW draws 2d or 3d arrow
  AEND = DRAW_ARROW (ASTR,AEND,ALN,PLOTOPT)
  the function draws an arrow with starting point ASTR and end point AEND, if ALN is empty;
  if ALN is specified, then it represents the arrow length
  with AEND interpreted as the arrow direction; in this case the function returns
  the end point coordinates of the arrow in vector AEND
  PLOTOPT is a data structure for controlling the arrow display with the following fields:
         TipSF: scale factor for controlling the size of the arrow tip (default = 1);
         ArWth: line width of arrow shaft (default = 1);
         ArClr: color of arrow shaft and tip (default = 'k');
         AbsSF: true or false to indicate absolute or relative to arrow length scaling
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Label_Model LABEL_MODEL displays element and node numbers and global axes in the current window
Plot_DispPath PLOT_DISPPATH plots biaxial displacement path in current window
Plot_ElemLoading PLOT_ELEMLOADING display element loading in current window
Plot_NodalForces PLOT_NODALFORCES display nodal forces in current window
Plot_SectionGeometry PLOT_SECTIONGEOMETRY plots cross section geometry in current window