Description of Draw_AxisCross
Home > Utilities > Plotting > Draw_AxisCross.m
Draw_AxisCross
PURPOSE
DRAW_AXISCROSS draw cross through the axes origin of the x-y data
SYNOPSIS
function Draw_AxisCross (Xlim,Ylim,PlotOpt)
DESCRIPTION
DRAW_AXISCROSS draw cross through the axes origin of the x-y data
  DRAW_AXISCROSS (XLIM,YLIM,PLOTOPT)
  the function draws a cross through the axes origin of the x-y data
  with a gray, solid line style and 1.5 pt line width;
  these properties can be controlled by specifying the fields LnStl, LnWth and Color
  of the optional argument PLOTOPT;
  XLIM and YLIM are 1x2 numerical arrays for the specification of the axes endpoints
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Plot_DispPath PLOT_DISPPATH plots biaxial displacement path in current window
Plot_LoadHistory PLOT_LOADHISTORY plots uniaxial or biaxial displacement and axial force history in current window
Plot_SectionGeometry PLOT_SECTIONGEOMETRY plots cross section geometry in current window
Plot_StoryDistr PLOT_STORYDISTR plots all columns of array XP against the row index
Plot_XYData PLOT_XYDATA plots one or more pairs of X and Y array columns