Description of LineProp4PlotSection
Home > Utilities > Plotting > LineProp4PlotSection.m
LineProp4PlotSection
PURPOSE
=========================================================================================
SYNOPSIS
function [Line] = LineProp4PlotSection()
DESCRIPTION
  =========================================================================================
  FEDEASLab - Release 5.1, July 2020
  Matlab Finite Elements for Design, Evaluation and Analysis of Structures
  Professor Filip C. Filippou (filippou@berkeley.edu)
  Department of Civil and Environmental Engineering, UC Berkeley
  Copyright(c) 1998-2020. The Regents of the University of California. All Rights Reserved.
  =========================================================================================
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Plot_Mesh4Circ PLOT_MESH4CIRC plots mesh for a circular disc or annulus in current window
Plot_Mesh4MultRectShape PLOT_MESH4MULTRECTSHAPE plot the mesh for section of several rectangular patches
Plot_SectionGeometry PLOT_SECTIONGEOMETRY plots cross section geometry in current window