Description of Plot_SectionGeometry
Home > Utilities > Plotting > Plot_SectionGeometry.m
Plot_SectionGeometry
PURPOSE
PLOT_SECTIONGEOMETRY plots cross section geometry in current window
SYNOPSIS
function Plot_SectionGeometry (SecData,PlotOpt)
DESCRIPTION
PLOT_SECTIONGEOMETRY plots cross section geometry in current window
  PLOT_SECTIONGEOMETRY(SECDATA,PLOTOPT)
  the function plots the geometry of the cross section in SECDATA in the current window
  PLOTOPT is a structure with the following fields:
  PLOTOPT.IPDsp : true or false for displaying the location of integration points
         .FibDsp: true or false for displaying the fiber (section discretization) outline
         .BarDsp: true or false for displaying the reinforcing bars, if present
         .AxsDsp: true or false for displaying the section reference axes
CROSS-REFERENCE INFORMATION
This function calls:
Draw_Arrow DRAW_ARROW draws 2d or 3d arrow
Draw_AxisCross DRAW_AXISCROSS draw cross through the axes origin of the x-y data
FontProp4PlotSection =========================================================================================
LineProp4PlotSection =========================================================================================
Plot_Mesh4Circ PLOT_MESH4CIRC plots mesh for a circular disc or annulus in current window
Plot_Mesh4MultRectShape PLOT_MESH4MULTRECTSHAPE plot the mesh for section of several rectangular patches
This function is called by: