Description of Plot_Model
Home > Utilities > Plotting > Plot_Model.m
Plot_Model
PURPOSE
PLOT_MODEL plots the original or deformed geometry of the structural model
SYNOPSIS
function Plot_Model (Model,U,MPlOpt)
DESCRIPTION
PLOT_MODEL plots the original or deformed geometry of the structural model
  PLOT_MODEL (MODEL,U,MPLOPT)
  the function plots in the current window the original or deformed geometry
  of the structural model in the data structure MODEL depending
  on the presence of the global displacement vector U in the argument list;
  MPLOPT is an optional data structure controlling the display;
  in its absense the function plots the model with default values;
  MPLOPT has the following fields:
    MAGF : magnification factor for deformed wireframe (default=10)
    NodSF: scale factor for size of node symbol (default=1)
    LnStl: line style (default = '-' for undeformed, '-.' for deformed configuration)
    LnWth: line width (default = 2)
    LnClr: wireframe and node color (default = 'b' for undeformed,
                                               'k' for deformed configuration)
    PlNod: switch for displaying node symbols (default ='no')
    PlBnd: switch for displaying boundary symbols (default='no')
    BsClr: color for boundary nodes and symbols (default=[0.6 0 0.6])
    PlJnt: switch for plotting joint offsets  (default='yes')
CROSS-REFERENCE INFORMATION
This function calls:
Draw_Cube DRAW_CUBE draws cube in current window
Get_ModelScale GET_MODELSCALE determines maximum and minimum element length in Model
Plot_BounCond PLOT_BOUNCOND plots symbols for boundary conditions of structural model
This function is called by:
Animate_EventSequence ANIMATE_EVENTSEQUENCE generate plot sequence with location of plastic hinges for each event
Animate_ResponsewHngHist ANIMATE_RESPONSEwHNGHIST interactive or recorded response and plastic hinge history
Plot_DeformedStructure PLOT_DEFORMEDSTRUCTURE plot deformed shape of the structure