URL: https://github.com/FEDEASLab/fdlb-0009
abstract: Algorithmic panel zone mesh generation for skeletal finite element models.
archive: $FEDEASLAB_DEV
archive_location: Gallery/fdlb-0009
author:
- family: Perez
  given: Claudio
collection-title: Panel Zones
id: fdlb-0009
medium: FEDEASLab Dev
programming-language: Matlab
system: FEDEASLab Dev
title: Panel Zone Mesh Generation
type: book
