Description of Create_RectwCovOutline
Home > Utilities > PreProcessing > Create_RectwCovOutline.m
Create_RectwCovOutline
PURPOSE
CREATE_RECTwCOVOUTLINE generate geometry outline for rectangular section with cover
SYNOPSIS
function [Outline,A,sy,sz] = Create_RectwCovOutline (Data)
DESCRIPTION
CREATE_RECTwCOVOUTLINE generate geometry outline for rectangular section with cover
  [OUTLINE,A,SY,SZ] = RECTwCOVOUTLINE (DATA)
  the function creates the data structure OUTLINE for rectangular section with cover
  with geometric properties in data structure DATA with the following fields:
       ndm = 2 or 3 for uniaxial or biaxial section model, respectively
       d   = depth
       b   = width
       cv(1:2) = cover thickness top/bottom, left/right (default = same thickness)
  the function returns the following information
       A  = area of the cross section
       SY = centroidal distance relative to section mid-depth
       SZ = centroidal distance relative to section mid-width
  Dimensions and coordinate system:
                        y ^
                          |
                      .---+---.
                      |   |   |
                      |   |   |
                z <---+---+   |  d
                      |       |
                      |       |
                      '-------'
                          b
CROSS-REFERENCE INFORMATION
This function calls:
Create_RectPatch CREATE_RECTPATCH generate corner coordinates of rectangular patch for given reference point
This function is called by:
Create_MultRectShape CREATE_MULTRECTSHAPE generate geometry outline and assign material properties for shape of rectangular patches
Create_ShapewMat CREATE_SHAPEwMAT generate geometry outline and assign material properties for shape STYPE