Description of Create_ShapewMat
Home > Utilities > PreProcessing > Create_ShapewMat.m
Create_ShapewMat
PURPOSE
CREATE_SHAPEwMAT generate geometry outline and assign material properties for shape STYPE
SYNOPSIS
function Shape = Create_ShapewMat (SType,Data)
DESCRIPTION
CREATE_SHAPEwMAT generate geometry outline and assign material properties for shape STYPE
  SHAPE = CREATE_MULTRECTSHAPE (STYPE,DATA)
  the function creates the data structure SHAPE with geometry outline information
  for the shape type in character variable STYPE
  using the geometry data in data structure DATA with the following fields:
  The function assigns the properties in the field MATDATA of the material type MATNAME
  to parts of the shape, as follows:
  MATNAME{1}, MATDATA{1} are assigned to the core  or flanges depending on shape
  MATNAME{2}, MATDATA{2} are assigned to the cover or webs    depending on shape (default=same as 1)
  MATNAME{3}, MATDATA{3} are assigned to the intersections of flange and web     (default=same as 1)
  The function returns the outline in cell array OUTLINE of data structure SHAPE;
  OUTLINE has at most 3 cells, each consisting of a 4 x N array where N is the number of
  rectangular patches that describe the outline of the corresponding part of the shape;
  OUTLINE{1} = rectangular patches for one or more flanges depending on shape
  OUTLINE{2} = rectangular patches for one or more webs    depending on shape;
  OUTLINE{3} = rectangular patches for flange and web intersections (if requested);
  each rectangular patch is described with a 4x1 vector of corner coordinates [y1;z1,y2;z2]
  where 1 refers to the upper left and 2 to the lower right corner of the rectangular patch;
  these coordinates are measured relative to the geometric centroid of the shape;
  the date structure shape also contains the area of the shape in field A,
  and the distances of its geometric centroid from the mid-depth D and mid-width B in
  fields CY and CZ, respectively.
CROSS-REFERENCE INFORMATION
This function calls:
Create_BoxOutline CREATE_BOXOUTLINE generate geometry outline for box section
Create_BoxwOvhOutline CREATE_BOXwOVHOUTLINE generate geometry outline for box section
Create_CSecOutline CREATE_CSECOUTLINE generate geometry outline for C-section
Create_ISecOutline CREATE_ISECOUTLINE generate geometry outline for I-section
Create_LSecOutline CREATE_LSECOUTLINE generate geometry outline for L-section
Create_RectOutline CREATE_RECTOUTLINE generate geometry outline for rectangular section
Create_RectwCovOutline CREATE_RECTwCOVOUTLINE generate geometry outline for rectangular section with cover
Create_SSecOutline CREATE_SSECOUTLINE generate geometry outline for C-section
Create_TSecOutline CREATE_TSECOUTLINE generate geometry outline for T-section
This function is called by: