Description of Create_BoxwOvhOutline
Home > Utilities > PreProcessing > Create_BoxwOvhOutline.m
Create_BoxwOvhOutline
PURPOSE
CREATE_BOXwOVHOUTLINE generate geometry outline for box section
SYNOPSIS
function [Outline,A,sy,sz] = Create_BoxwOvhOutline (Data)
DESCRIPTION
CREATE_BOXwOVHOUTLINE generate geometry outline for box section
  [OUTLINE,A,SY,SZ] = CREATE_BOXwOVHOUTLINE (DATA)
  the function creates the data structure OUTLINE for box section with overhang
  with geometric properties in data structure DATA with the following fields:
       d  = total depth
       bf = flange width
       tf = flange thickness
       tw = web    thickness
       bo = overhang width
       Loc = 1 or 2 for flange above or below the z-axis
       FlgOpt = true/false, FlgOpt = true : single outline for flange
       WebOpt = true/false, WebOpt = true : single outline for web
       FlgOpt = false + WebOpt = false : create separate outline for web-flange intersection
  the function returns the following information
       A  = area of the cross section
       SY = centroidal distance relative to section mid-depth
       SZ = centroidal distance relative to section mid-width
  Dimensions and coordinate system:
                               y ^
               bo                |               bo
           .----------.----------+----------.----------.
           |                  tf |                     |
           .----------.   .------|------.   . ---------.
                      |   |      |      |   |
                z <-------+----- +      |   |  d
                      |tw |             |   |
                      |   '-------------'   |
                      |         tf          |
                      '---------------------'
                                bf
CROSS-REFERENCE INFORMATION
This function calls:
Create_RectPatch CREATE_RECTPATCH generate corner coordinates of rectangular patch for given reference point
This function is called by:
Create_MultRectShape CREATE_MULTRECTSHAPE generate geometry outline and assign material properties for shape of rectangular patches
Create_ShapewMat CREATE_SHAPEwMAT generate geometry outline and assign material properties for shape STYPE