abstract: An exploration into how the yield surface of certain cross sections evolve
  as they undergo combined flexural and axial loading into the inelastic range.
author:
- family: Perez
  given: Claudio
collection-title: Section analysis
id: fdlb-0011
programming-language: Matlab
distribution: FEDEASLab Dev
title: Yield surface evolution
