Home > src > Other > Create_PanelZone.m
Create_PanelZone
PURPOSE
% Clear memory and close any open windows
SYNOPSIS
This is a script file.
DESCRIPTION
% Clear memory and close any open windows
CROSS-REFERENCE INFORMATION
This function calls:
CleanStart CLEANSTART initializes workspace for new analysis
Create_MRFrame CREATE_FRAME generation of nodes and elements for regular N-story, M-bay MR frame
Units % Script file for common unit definition with Imperial units as default
This function is called by: