URL: https://github.com/FEDEASLab/BasicExamples
archive: $FEDEASLAB_DEV
archive_location: Gallery/BasicExamples
collection-title: Linear analysis
id: fdlb-0010
medium: CE220
programming-language: Matlab
system: CE220
title: Basic Collection
type: book
