Description of Plot_PlasticHinges
Home > Utilities > Plotting > Plot_PlasticHinges.m
Plot_PlasticHinges
PURPOSE
PLOT_PLASTICHINGES display plastic hinge locations in current window
SYNOPSIS
function Plot_PlasticHinges (Model,ElemData,U,Post,PlotOpt)
DESCRIPTION
PLOT_PLASTICHINGES display plastic hinge locations in current window
  PLOT_PLASTICHINGES (MODEL,ELEMDATA,U,POST,PLOTOPT)
  the function displays in the current window the plastic hinge locations
  for the elements of the structural model in data structure MODEL (only 2d models for now).
  There are two options for supplying the plastic capacities and basic force values:
      (a) ELEMDATA is a vector of plastic capacities and
  or, (b) ELEMDATA is a cell array with the plastic capacities in fields Np for the axial,
          and Mp for the flexural capacity.
  In the presence of the global dof displacements U the plastic hinges are displayed
  in the deformed configuration otherwise in the undeformed.
  There are three options for POST:
      (a) POST is the vector of basic forces Q corresponding to case (a) of ELEMDATA
      (b) POST is the vector of plastic deformation increments DVPL in which case
          ELEMDATA is either empty or a character variable with the N-M interaction option NMOPT;
          NMOPT can be one of three options: 'None' (default), 'Dmnd' or 'AISC';
      (c) POST is a cell array with post-processing information in the fields of POST.ELEM{el}.
  PLOTOPT is an optional data structure controlling the display;
  in its absense the function displays the plastic hinges with default properties;
  PLOTOPT has the following fields:
    EList: list of elements for which plastic hinges are displayed (default all elements)
    HngSF: scale factor for size of plastic hinge symbol                  (default = 1)
    HOfSF: factor for offset of the plastic hinge symbol from element end (default = 1)
    FHClr: color for flexural hinges                                      (default='r')
    CHClr: color for column hinges with N-M interaction               (default = [1 0.6 0])
    AHClr: color for axial hinges in truss elements                   (default = [1 0.6 0])
    tol:   relative tolerance for plastic capacity check;
           absolute tolerance for plastic rotation check              (default=1e-6)
CROSS-REFERENCE INFORMATION
This function calls:
Get_ModelScale GET_MODELSCALE determines maximum and minimum element length in Model
Plot_Hinge4Elem PLOT_HINGE4ELEM plot releases or plastic hinges for truss or frame element
This function is called by:
Animate_EventSequence ANIMATE_EVENTSEQUENCE generate plot sequence with location of plastic hinges for each event
Animate_ResponsewHngHist ANIMATE_RESPONSEwHNGHIST interactive or recorded response and plastic hinge history